version: 2

sources:
  - name: cdc_wonder_raw
    description: "Raw CDC WONDER synthetic opioid mortality data"
    tables:
      - name: d77_official_1999_2020
        description: "Official mortality data from 1999-2020 (Multiple Cause of Death)"
        columns:
          - name: year
            description: "Year of death"
            tests:
              - not_null
          - name: state
            description: "State name"
            tests:
              - not_null
          - name: county
            description: "County name"
          - name: deaths
            description: "Number of deaths"
            tests:
              - not_null
          - name: population
            description: "Population count"
          - name: crude_rate
            description: "Crude death rate per 100,000 population"
          - name: age_adjusted_rate
            description: "Age-adjusted death rate per 100,000 population"
            
      - name: d157_official_2018_2023
        description: "Official mortality data from 2018-2023 (Multiple Cause of Death, Single Race)"
        columns:
          - name: year
            description: "Year of death"
            tests:
              - not_null
          - name: state
            description: "State name"
            tests:
              - not_null
          - name: county
            description: "County name"
          - name: deaths
            description: "Number of deaths"
            tests:
              - not_null
          - name: population
            description: "Population count"
          - name: crude_rate
            description: "Crude death rate per 100,000 population"
          - name: age_adjusted_rate
            description: "Age-adjusted death rate per 100,000 population"
            
      - name: d176_provisional_2023_current
        description: "Provisional mortality data from 2023-current"
        columns:
          - name: year
            description: "Year of death"
            tests:
              - not_null
          - name: state
            description: "State name"
            tests:
              - not_null
          - name: county
            description: "County name"
          - name: deaths
            description: "Number of deaths"
            tests:
              - not_null
          - name: population
            description: "Population count"
          - name: crude_rate
            description: "Crude death rate per 100,000 population"
          - name: age_adjusted_rate
            description: "Age-adjusted death rate per 100,000 population"
