version: 2

sources:
  - name: cdc_wonder_raw
    description: "Raw CDC WONDER synthetic opioid mortality data"
    schema: main
    tables:           
      - name: d176_provisional_2018_current
        description: "Provisional mortality data from 2018-current"
