name: 'fentanyl_awareness'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fentanyl_awareness'

# These configurations specify where dbt should look for different types of files.
model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
models:
  fentanyl_awareness:
    staging:
      +materialized: view
    marts:
      +materialized: table

# Configuring seeds
seeds:
  fentanyl_awareness:
    +quote_columns: true
